homework_09/ordersbook/employees/urls.py
from django.contrib import admin
from django.urls import path
from .views import EmployeesListView, EmployeeDetailView, EmployeeDeleteView, EmployeeCreateView


app_name = "employees"

urlpatterns = [

    path("", EmployeesListView.as_view(), name="index"),

    path("<int:pk>", EmployeeDetailView.as_view(), name="details"),

    path("<int:pk>/confirm-delete", EmployeeDeleteView.as_view(), name="delete-employee"),

    path("create/", EmployeeCreateView.as_view(), name="create-employee"),
]

homework_09/ordersbook/myauth/urls.py
from django.urls import path

from .views import MeView, LoginView, LogoutView, secret_view

app_name = "myauth"

urlpatterns = [

    path("secret/", secret_view, name="secret"),

    path("me/", MeView.as_view(), name="me"),

    path("login/", LoginView.as_view(), name="login"),

    path("logout/", LogoutView.as_view(), name="logout"),
]

homework_09/ordersbook/orders/urls.py
from django.contrib import admin
from django.urls import path
from .views import OrdersListView

app_name = "orders"

urlpatterns = [
    path("", OrdersListView.as_view(), name="index"),
]

homework_09/ordersbook/ordersbook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employees/', include("employees.urls")),
    path('orders/', include("orders.urls")),
    path('auth/', include("myauth.urls")),
]

homework_09/ordersbook/employees/models.py
from django.db import models


class JobTitles(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Employee(models.Model):
    surname = models.CharField(max_length=64, null=False)
    firstname = models.CharField(max_length=64, null=False)
    patronymic = models.CharField(max_length=64, null=False)
    personnel_number = models.CharField(max_length=64, unique=True, null=False)
    email = models.CharField(max_length=64, null=False)
    job = models.ForeignKey(JobTitles, on_delete=models.PROTECT, related_name="employee")
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.surname} {self.firstname} ({self.job})"

homework_09/ordersbook/myauth/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import AbstractUser


UserModel: AbstractUser = get_user_model()

homework_09/ordersbook/orders/models.py
from django.db import models


class Order(models.Model):
    name = models.CharField(max_length=64, null=False)
    worker = models.ManyToManyField("employees.employee", related_name="orders")

homework_09/ordersbook/employees/forms.py
from django.forms import ModelForm, CharField
from django.forms.widgets import Widget
from .models import Employee


class AnimalCreateForm(ModelForm):
    class Meta:
        model = Employee
        fields = "surname", "firstname", "patronymic", "personnel_number", "email", "job"

    surname = CharField(max_length=40, label="Фамилия")
    firstname = CharField(max_length=40, label="Имя")
    patronymic = CharField(max_length=40, label="Отчество")
    personnel_number = CharField(max_length=8, label="Табельный номер")
    email = CharField(max_length=40, label="Email")
    # job = CharField(max_length=40, label="Должность")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            # print(name, field, field.widget)
            widget: Widget = field.widget
            widget.attrs["class"] = "form-control"

homework_09/ordersbook/myauth/forms.py
from django.contrib.auth.forms import AuthenticationForm as AuthenticationFormGeneric
from django.forms import Widget


class AuthenticationForm(AuthenticationFormGeneric):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            # print(name, field, field.widget)
            widget: Widget = field.widget
            widget.attrs["class"] = "form-control"

homework_09/ordersbook/employees/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.urls import reverse_lazy, reverse

from .models import Employee, JobTitles
from .forms import AnimalCreateForm
from django.views.generic import ListView, DetailView, DeleteView, CreateView


class EmployeesListView(ListView):

    template_name = "employees/index.html"
    context_object_name = "employees"

    queryset = (
        Employee.objects
        .select_related("job")
        .filter(archived=False)
        .order_by('pk').all()
        )


class EmployeeDetailView(DetailView):
    template_name = "employees/details.html"
    context_object_name = "employee"
    queryset = (Employee.objects.select_related("job"))


class EmployeeDeleteView(DeleteView):
    model = Employee
    success_url = reverse_lazy("employees:index")
    context_object_name = "employee"

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class EmployeeCreateView(CreateView):
    # model = Employee
    # fields = ["surname", "firstname", "patronymic", "personnel_number", "email", "job"]
    # success_url = reverse_lazy("employees:index")

    model = Employee
    form_class = AnimalCreateForm

    def get_success_url(self):
        return reverse("employees:details", kwargs={"pk": self.object.pk})

homework_09/ordersbook/myauth/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from .forms import AuthenticationForm
from django.contrib.auth.views import (
    LoginView as LoginViewGeneric,
    LogoutView as LogoutViewGeneric,
)


@login_required
def secret_view(request):
    return HttpResponse("secret info: ...")


class MeView(TemplateView):
    template_name = "myauth/me.html"


class LoginView(LoginViewGeneric):
    form_class = AuthenticationForm
    next_page = reverse_lazy("myauth:me")


class LogoutView(LogoutViewGeneric):
    next_page = reverse_lazy("myauth:me")

homework_09/ordersbook/orders/views.py
from django.http import HttpRequest
from django.shortcuts import render
from .models import Order
from django.views.generic import ListView, DetailView


class OrdersListView(ListView):

    template_name = "orders/index.html"
    context_object_name = "orders"

    queryset = (
        Order.objects
            #.select_related("job")
            .prefetch_related("worker")
            .order_by('pk').all()
        )

homework_09/ordersbook/employees/templates/employees/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>

  <body>


  <nav class="navbar navbar-expand-sm bg-light">
  <div class="container-fluid">


          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Меню
          </a>
{#          <ul class="dropdown-menu">#}
{#            <li><a class="dropdown-item" href="/">Home</a></li>#}
{#            <li><a class="dropdown-item" href="/about">About</a></li>#}
          </ul>


{#    <a class="navbar-brand" href="#">Zoo</a>#}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'employees:index' %}">
            Сотрудники</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'orders:index' %}">
            Наряды</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myauth:me' %}">{{ user }}</a>
        </li>
{#        <li class="nav-item">#}
{#          <a class="nav-link disabled">Disabled</a>#}
{#        </li>#}
      </ul>

      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'myauth:logout' %}">Logout</a>
          {% else %}
            <a class="nav-link" href="{% url 'myauth:login' %}">Login</a>
          {% endif %}
        </li>
      </ul>

    </div>
  </div>
</nav>


  <div class="container">
     {% block body %}
        <h1>Hello, world!</h1>
     {% endblock %}
  </body>
  </div>

</html>

homework_09/ordersbook/employees/templates/employees/details.html
{% extends "employees/base.html" %}

{% block title %}
    {{ employee.name }} details
{% endblock %}

{% block body %}
    <h2>Сотрудник <strong>{{ employee.name }}</strong></h2>
    <div class="p-4">
      <b><p>Фамилия:</b> {{ employee.surname }}</p>
       <b><p>Имя:</b> {{ employee.firstname }}</p>
       <b><p>Отчество:</b> {{ employee.patronymic }}</p>
       <b><p>Табельный номер:</b> {{ employee.personnel_number }}</p>
       <b><p>Email:</b> {{ employee.email }}</p>
       <b><p>Должность:</b> {{ employee.job }}</p>
    </div>

    <div class="">
     <a class="btn btn-sm btn-outline-danger"
             href="{% url 'employees:index' %}">Список сотрудников</a>
    </div>
{% endblock %}

homework_09/ordersbook/employees/templates/employees/employee_confirm_delete.html
{% extends 'employees/base.html' %}

{% block title %}
  Delete employee
{% endblock %}

{% block body %}

  <form method="post">{% csrf_token %}
   <b> <p>Вы действительно хотите удалить сотрудника? </p></b>
      <b> <p>{{ employee.surname }} {{ employee.firstname }} {{ employee.patronymic }} (таб. номер {{ employee.personnel_number }})</p></b>
    {{ form }}
    {# <a href="{% url 'animals:kind-details' kind.id %}"></a>#}
    <a
      class="btn btn-secondary"
      href="{% url 'employees:index' %}">
      Назад к списку
    </a>
    <button class="btn btn-danger" type="submit">
      Удалить
    </button>
  </form>
{% endblock %}

homework_09/ordersbook/employees/templates/employees/employee_form.html
{% extends 'employees/base.html' %}

{% block title %}
  Создать сотрудника
{% endblock %}

{% block body %}
  <h1>Создать сотрудника</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button
      class="btn btn-success"
      type="submit">
      Создать
    </button>
  </form>
{% endblock %}

homework_09/ordersbook/employees/templates/employees/index.html
{% extends "employees/base.html" %}

{% block title %}
    Сотрудники
{% endblock %}

{% block body %}
    <div class="my-2">
    <h3>Сотрудники</h3>
    <div>

  <div class="row">
    <div class="col col-md-7">
       <ul class="list-group">
           {% for empl in object_list %}
               <li class="list-group-item">
                <a class="text-decoration-none" href="{% url 'employees:details' empl.pk %}">
                   {{ empl.surname }} {{ empl.firstname }}</a>
                   ({{ empl.job }})

                {% if perms.employees.delete_employee %}
                    <span class="float-end">
                        <a class="btn btn-sm btn-outline-danger"
                            href="{% url 'employees:delete-employee' empl.pk %}">
                            Удалить </a>
                    </span>
                {% endif %}

               </li>
           {% endfor %}
        </ul>
    </div>
  </div>

{#  {% if user.is_authenticated %}#}

  {% if perms.employees.create_employee %}
    <div class="my-2">
        <a class="btn btn-outline-info"
           href="{% url 'employees:create-employee' %}"
         > Новый сотрудник </a>
    </div>
  {% endif %}

{% endblock %}

homework_09/ordersbook/myauth/templates/myauth/me.html
{% extends 'employees/base.html' %}

{% block title %}
  User info
{% endblock %}

{% block body %}
  <h1>Hello {% firstof user.first_name user.email user.username user %}</h1>
{% endblock %}

homework_09/ordersbook/orders/templates/orders/index.html
{% extends "employees/base.html" %}

{% block title %}
    Наряды
{% endblock %}

{% block body %}
    <div class="my-2">
    <h3>Наряды</h3>
    <div>

    <div>
       <ul class="list-group">
           {% for order in orders %}
               <ul class="list-group-item">
{#                <a href="{% url 'employees:details' empl.pk %}">{{ empl.name }}</a>#}
                   <b> {{ order.name }}</b>
               <BR>

                {#<b>Рабочие:</b> {{ order.worker.all|join:", " }}#}

               <div class="my-2">
                {% for name in order.worker.all %}
                  {{ name }}
                  <BR>
                {% endfor %}
               </div>

               </ul>

           {% endfor %}


        </ul>
    </div>

{% endblock %}